[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "email-validator>=2.3.0",
    "fastapi>=0.142.2",
    "httpx>=0.28.1",
    "pwdlib[argon2]>=0.3.1",
    "pydantic>=2.0",
    "pyjwt>=2.15.1",
    "pytest>=9.1.1",
    "python-dotenv>=1.2.4",
    "sqlalchemy>=2.0",
    "uvicorn[standard]>=0.54.0",
]

[tool.pytest.ini_options]
pythonpath = ["backend"]
